# Generated by Django 5.2.14 on 2026-05-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=100, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(max_length=255)),
                ('semester', models.IntegerField(default=1)),
                ('batch_year', models.IntegerField()),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('total_courses_enrolled', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('current_gpa', models.FloatField(default=0.0)),
                ('enrollment_date', models.DateField()),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
