# Generated by Django 5.2.14 on 2026-05-23 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date(2026, 5, 23), help_text='Date of admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/admission_letters/'),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_10th',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_12th',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default=1, help_text='Current year of study'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/identity_proofs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/medical/'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
