# Generated by Django 5.2.14 on 2026-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accreditation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='organization_documents/accreditation/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='accreditation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='accreditation_type',
            field=models.CharField(choices=[('NAAC', 'NAAC'), ('ACCBIND', 'ACCBIND'), ('NBA', 'NBA'), ('OTHER', 'Other'), ('NONE', 'None')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='organization_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='principal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='principal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='organization_documents/registration/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='university_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
