# Generated by Django 5.2.14 on 2026-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/experience/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/identity/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='performance_rating',
            field=models.FloatField(default=0.0, help_text='Average performance rating'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='research_publications',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/research/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_license',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(choices=[('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('PHD', 'PhD'), ('POSTDOC', 'Post-Doctorate'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
