# Generated by Django 5.2.14 on 2026-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportteammember',
            name='assigned_categories',
            field=models.CharField(blank=True, help_text='Comma-separated categories', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='average_resolution_time',
            field=models.IntegerField(default=0, help_text='In hours'),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='support_documents/certifications/'),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='support_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='support_documents/identity/'),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated languages', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning (6 AM - 2 PM)'), ('AFTERNOON', 'Afternoon (2 PM - 10 PM)'), ('NIGHT', 'Night (10 PM - 6 AM)'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='supportteammember',
            name='total_tickets_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
